@web_api_with_ef_core_odata_HostAddress = http://localhost:5154/odata

// Get products list
GET {{web_api_with_ef_core_odata_HostAddress}}/Products
Accept: application/json

###

// Get product by ID
GET {{web_api_with_ef_core_odata_HostAddress}}/Products(1)
Accept: application/json

###

// Get products with expanded category
GET {{web_api_with_ef_core_odata_HostAddress}}/Products?$expand=Category
Accept: application/json

###

// Get products filtered by category name 'Electronics' with expanded category
GET {{web_api_with_ef_core_odata_HostAddress}}/Products?$filter=Category/Name%20eq%20'Electronics'&$expand=Category
Accept: application/json

###

// Create a new product
POST {{web_api_with_ef_core_odata_HostAddress}}/Products
Content-Type: application/json
Accept: application/json

{
  "Name": "OData test product",
  "CategoryId": 1,
  "Price": 2999.99
}

###

// Update an existing product
PUT {{web_api_with_ef_core_odata_HostAddress}}/Products(1)
Content-Type: application/json
Accept: application/json

{
  "Id": 1,
  "Name": "Modified product",
  "CategoryId": 2,
  "Price": 3999.99
}

###

// Delete a product
DELETE {{web_api_with_ef_core_odata_HostAddress}}/Products(5)

###

// Filter products with price greater than 1000
GET {{web_api_with_ef_core_odata_HostAddress}}/Products?$filter=Price%20gt%201000
Accept: application/json

###

// Order products by price descending
GET {{web_api_with_ef_core_odata_HostAddress}}/Products?$orderby=Price%20desc
Accept: application/json

###

// Select only Name and Price fields
GET {{web_api_with_ef_core_odata_HostAddress}}/Products?$select=Name,Price
Accept: application/json

###

// Paginate/Get top 2 products, skipping the first one
GET {{web_api_with_ef_core_odata_HostAddress}}/Products?$top=2&$skip=1
Accept: application/json

###

// Get categories list
GET {{web_api_with_ef_core_odata_HostAddress}}/Categories
Accept: application/json

###

// Get category by ID
GET {{web_api_with_ef_core_odata_HostAddress}}/Categories(1)
Accept: application/json

###

// Create a new category
POST {{web_api_with_ef_core_odata_HostAddress}}/Categories
Content-Type: application/json
Accept: application/json

{
  "Name": "OData test category"
}

###

// Update an existing category
PUT {{web_api_with_ef_core_odata_HostAddress}}/Categories(1)
Content-Type: application/json
Accept: application/json

{
  "Id": 1,
  "Name": "Modified product"
}

###

// Delete a category
DELETE {{web_api_with_ef_core_odata_HostAddress}}/Categories(4)

###

// Filter categories with name containing 'Electronics'
GET {{web_api_with_ef_core_odata_HostAddress}}/Categories?$filter=Name%20contains%20'Electronics'
Accept: application/json

###

// Order categories by name descending
GET {{web_api_with_ef_core_odata_HostAddress}}/Categories?$orderby=Name%20desc
Accept: application/json

###

// Select only Name fields
GET {{web_api_with_ef_core_odata_HostAddress}}/Categories?$select=Name
Accept: application/json

###

// Paginate/Get top 2 products, skipping the first one
GET {{web_api_with_ef_core_odata_HostAddress}}/Categories?$top=1&$skip=1
Accept: application/json

###